{% set version = "1.86.0" %}
{% set commit = "33cbf70dec4f64836a26dcb4a885cb09b7279dd3" %}

package:
  name: nn
  version: {{ version }}

source:
  url: https://github.com/sakov/nn-c/archive/{{ commit }}.tar.gz
  sha256: eb00f951bbe36e933d16de520db44acf93e9becf6e0182e391c1c7f98441972b

build:
  number: 3
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
  host:

test:
  commands:
    - nnbathy -V
    - conda inspect linkages -p $PREFIX nn  # [not win]
    - conda inspect objects -p $PREFIX nn  # [osx]

about:
  home: https://github.com/sakov/nn-c
  license: BSD 2-Clause (bundled triangle code is non-free for commercial use)
  license_file: LICENSE
  summary: 'Natural Neighbours interpolation.'

extra:
  recipe-maintainers:
    - ocefpaf
