appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: QuLm3rozb8MCKyKYzi4NSv24xOg4zfJ0nfeGeMc2HamiYrOyqh9ExuyXoIRU4U3JMSHffhmQxsPX2HGH2SiE7HY0a9ZGoSpRUyECc786aEg9ru8ODZU6o/CCAmFJ+CGNU/7XawkNh0hHiu052s72xkDx9ca0vY53uR+8XdIyfNslfpfVWlnt8R098F5KG74wRS1UelZctnC9XdT8lOODI/nwn+otO/VpYVCWsZLyk9YlfceOmNTdgoAV1zG+YvbsL5J494Vo4f7siGyWRRjP1vkdGdFeZ4+2pXzvL/HxzQJrgNPcMwHzqixoBgg8qpuDMmhDMXkgk0lOc1SCCJ7WCt4Q406NBauBpDf/xxPg5NebL0+pWL3Di4ZfMZ5bv6XlGN8qjfi4r25PNcQPou1i83cIEwZM4Oun0WstesTVeuY0x6BUI8BBgYDL8cV6h2T4w7jz3BHjx8kSaP/yM7XDR9Esa5lJ22BWxuk5tIzQaCkOPvhTdR58lKDI2d4UA1TiuinS3mny190fQDjzPqJUIt5OUnuKqtd4wiB7Cl5s7M6m6gLm02iV8KuUNEhN/UWSBYVn4QAi9SO4Y4UEaVf6+E+ljZN2nuqjs6NG6El0uYc0RY/AcZZLQzk7iilkK7CaB2ticFUqCFEops+uvaLA0pw7KPs2knvjrsirSgfmot8=}
conda_forge_output_validation: true
